### ISSUE TITLE
Link in left menu opens two tabs

### ISSUE THREAD

**Issue by oleteacher** [ajiho/quicktab#19]
### 先决条件

- [X] 我确认已查阅文档:https://ajiho.github.io/quicktab ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/ajiho/quicktab/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。

### 报告类型

BUG报告

### 使用版本

v 0.0.8

### 问题描述

Hello kind sir, sorry I do not speak Chinse.  Thank you for the [demo ](https://stackblitz.com/edit/stackblitz-starters-yqjdcp?file=index.html)

Moving conversation from AdminLTE repository.

I attempt to add links in left sidebar menu and have issue. Two (2) tabs are opened:

```
<li class="nav-item">
	<a href="pages/widgets.html" class="nav-link">
	  <i class="nav-icon fas fa-th"></i>
	  <p>
		Widgets
		<span class="right badge badge-danger">New</span>
	  </p>
	</a>
</li>
<li class="nav-item">
	<a href="#"
	class="nav-link"
	data-qt-tab-url="https://example.com"
	data-qt-tab-title="Example"
	data-qt-tab-closable="true"
	data-qt-target="#qtab"
	>Example</a>
</li>

<li class="nav-item">
	<a href="#"
	class="nav-link"
	data-qt-tab-url="contact.html"
	data-qt-tab-title="Contact"
	data-qt-tab-closable="true"
	data-qt-target="#qtab"
	>Contact</a>
</li>
```

![image](https://github.com/user-attachments/assets/5b7f8d5e-b2a9-4c5e-afde-749d9e6bcadd)

No issue using top navbar home and contact links, they function perfect and only open one (1) tab.

Kindly help me to open only one tab for each link in sidebar menu.

How properly add icon to items in left sidebar menu like `<i class="nav-icon fas fa-th"></i>`

### 浏览器

Edge latest

**Comment by codinginbarn** [comment]
Once I got off the small screen phone and to my desktop, the issue I experience was:

// const url = `home.html?id=${num}`;

I see better now, and this non-issue should be closed.

**Comment by oleteacher** [comment]
Had some help and got off the small screen phone to my desktop. See my issue:

`// const url = 'home.html?id=${num}';`

Changed to `const url = $link.attr('href');` and removed the  `+ num;`

Everything is working great, issue entirely my fault.
